# Generated by Django 5.0.6 on 2024-06-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('year', models.CharField(max_length=40)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
